version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: book_postgres
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookuser -d bookdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: book_app
    environment:
      DATABASE_URL: postgresql+asyncpg://bookuser:bookpass@postgres:5432/bookdb
      SECRET_KEY: your-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic

volumes:
  postgres_data: